version: "2.4"

networks:
  software-proyect:
    name: network-my-proyects
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172,30.0.1
  software-config:
    name: network-config-server
    external: true

services:
  ms-discovery:
    image: ms-discovery:0.0.1
    mem_limit: 150m
    ports:
      - "8763:8763"
    networks:
      - software-proyect
      - software-config
    #environment:
    #  - "EUREKA_URI=http://192.168.0.4:8763/eureka"
    volumes:
      - "/tmp/local/logs:/opt/arquitectura/logs"
  #ms-config-server:
    #image: ms-config-server:0.0.1
    #mem_limit: 150m
    #ports:
      #- "8887:8887"
    #networks:
      #- software
    #environment:
      #- "ZIPKIN_URL=http://192.168.0.4:9411"
      #- "EUREKA_URI=http://192.168.0.4:8763/eureka"
    #volumes:
      #- "/tmp/local/logs:/opt/arquitectura/logs"
    #depends_on:
      #ms-discovery:
        #condition: service_started
  ms-gateway:
    image: ms-gateway:0.0.1
    mem_limit: 150m
    ports:
      - "8181:8181"
    networks:
      - software-proyect
      - software-config
    environment:
      - "ZIPKIN_URL=http://192.168.0.4:9411"
      - "EUREKA_URI=http://ms-discovery:8763/eureka"
      - "CONFIG_URI=http://ms-config-server:8887"
    volumes:
      - "/tmp/local/logs:/opt/arquitectura/logs"
    depends_on:
      ms-discovery:
        condition: service_started
  ms-student:
    image: ms-student:0.0.2
    mem_limit: 200m
    ports:
      - "6945:6945"
    networks:
      - software-proyect
      - software-config
    environment:
      - "ZIPKIN_URL=http://192.168.0.4:9411"
      - "EUREKA_URI=http://ms-discovery:8763/eureka"
      - "CONFIG_URI=http://ms-config-server:8887"
    volumes:
      - "/tmp/local/logs:/opt/arquitectura/logs"
    depends_on:
      ms-discovery:
        condition: service_started
  ms-teacher:
    image: ms-teacher:0.0.1
    mem_limit: 200m
    ports:
      - "7878:7878"
    networks:
      - software-proyect
      - software-config
    environment:
      - "ZIPKIN_URL=http://192.168.0.4:9411"
      - "EUREKA_URI=http://ms-discovery:8763/eureka"
      - "CONFIG_URI=http://ms-config-server:8887"
    volumes:
      - "/tmp/local/logs:/opt/arquitectura/logs"
    depends_on:
      ms-discovery:
        condition: service_started
  ms-course:
    image: ms-course:0.0.1
    mem_limit: 200m
    ports:
      - "8743:8743"
    networks:
      - software-proyect
      - software-config
    environment:
      - "ZIPKIN_URL=http://192.168.0.4:9411"
      - "EUREKA_URI=http://ms-discovery:8763/eureka"
      - "CONFIG_URI=http://ms-config-server:8887"
    volumes:
      - "/tmp/local/logs:/opt/arquitectura/logs"
    depends_on:
      ms-discovery:
        condition: service_started
      #ms-config-server:
        #condition: service_started