spring:
  application:
    name: msStudent
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}
  h2:
    console:
      enabled: true
server:
  port: ${SERVER_PORT:6545}

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8763/eureka}